{% set name = "robotframework-mqttlibrary" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/robotframework-mqttlibrary-{{ version }}.tar.gz
  sha256: b40d426cb33242b05b7f03a32f56bcb0c601f4568553a09dbbbcff17d0e900de

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - robotframework
    - paho-mqtt

test:
  imports:
    - MQTTLibrary
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/randomsync/robotframework-mqttlibrary
  summary: MQTT Keyword Library Robot Framework
  doc_url: https://pythonhosted.org/robotframework-mqttlibrary/
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nisharai1
